name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pandas matplotlib seaborn azure-storage-blob

      - name: Run Python Syntax Check
        run: |
          python -m py_compile data_analysis.py
          python -m py_compile lambda_function.py

      - name: Build Docker Image
        run: |
          docker build -t diet-analysis .